services:

  vectordb:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    image: docker.io/qdrant/qdrant:v1.9.2
    # image: qdrant/qdrant:v1.9.2-unprivileged # Unprivileged don't work when mounting a volume
    restart: unless-stopped
    volumes:
      - ./data/qdrant:/qdrant/storage
      # - ./qdrant_config.yml:/qdrant/config/production.yaml
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
    networks:
      - podmanfix2
    # ports:
    #   - 6333:6333
    #   - 6334:6334
    # command:
    #   - ./qdrant --config-path /qdrant/config/production.yaml

  api:
    build: .
    depends_on:
      - vectordb
    ports:
      - 443:80
    environment:
      - MAX_WORKERS=2
      # cf. https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/gunicorn_conf.py
    volumes:
      - ./data/fastembed_cache:/tmp/fastembed_cache
      - ./data/logs:/logs
      - ./src:/app/src
    networks:
      - podmanfix2
    # entrypoint: uvicorn src.expasy_chat.api:app --host 0.0.0.0 --port 80
    env_file:
      - .env

# NOTE: Podman networks are completly broken so we need to increment the network name when it stops working

networks:
  podmanfix2:
    driver: bridge

# podman-compose down && podman network prune -f
# podman exec -it expasy-chat_api_1 bash -c "apt-get update && apt-get install -y telnet && telnet vectordb 6334"
